image:
  repository: 495456316536.dkr.ecr.us-west-1.amazonaws.com/my-django-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilization: 70

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: false

config:
  POSTGRES_PORT: 5432
  POSTGRES_HOST: postgres
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd
  ALLOWED_HOSTS: localhost,.us-west-2.elb.amazonaws.com

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: pass12345
        username: django_user
        database: django_db
        password: pass12345
  primary:
    persistence:
      size: 2Gi
